/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    pages: Page;
    hero: Hero;
    'hero-slides': HeroSlide;
    services: Service;
    'pricing-plans': PricingPlan;
    testimonials: Testimonial;
    'site-settings': SiteSetting;
    'about-items': AboutItem;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'about-items': AboutItemsSelect<false> | AboutItemsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  content?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  title: string;
  description: string;
  primaryButtonText?: string | null;
  secondaryButtonText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images displayed in the hero section image slider. Add multiple images — they will auto-slide every 3 seconds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  image: number | Media;
  /**
   * Short description of the image (used for accessibility)
   */
  alt: string;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Emoji icon (e.g., 🌐, 🖥️, 🗄️) — used if Lucide Icon is not set
   */
  icon?: string | null;
  /**
   * Lucide icon — overrides emoji icon above
   */
  iconName?:
    | (
        | 'Zap'
        | 'ShieldCheck'
        | 'Cloud'
        | 'Headphones'
        | 'Server'
        | 'Database'
        | 'Globe'
        | 'TrendingUp'
        | 'CheckCircle'
        | 'Star'
        | 'Award'
        | 'Users'
        | 'Cpu'
        | 'Lock'
        | 'BarChart2'
        | 'Rocket'
        | 'Shield'
        | 'Settings'
        | 'Mail'
        | 'Phone'
        | 'MapPin'
        | 'ArrowRight'
        | 'Clock'
        | 'Activity'
        | 'HardDrive'
        | 'Wifi'
        | 'Code'
        | 'Package'
      )
    | null;
  title: string;
  description: string;
  /**
   * External image URL for the service card (optional)
   */
  imageUrl?: string | null;
  /**
   * Upload an image for the service card (overrides URL)
   */
  serviceImage?: (number | null) | Media;
  /**
   * Link for the Learn More button
   */
  learnMoreUrl?: string | null;
  /**
   * Order in which services appear
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  name: string;
  /**
   * Price in format like "$2.99"
   */
  price: string;
  period: string;
  description?: string | null;
  features: {
    feature: string;
    id?: string | null;
  }[];
  /**
   * Mark this plan as popular/featured
   */
  isPopular?: boolean | null;
  /**
   * CTA button label for this plan
   */
  buttonText?: string | null;
  /**
   * CTA button link URL
   */
  buttonUrl?: string | null;
  /**
   * Order in which plans appear
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * Job title or company (e.g. "CEO, Acme Corp")
   */
  role?: string | null;
  /**
   * Company name (optional)
   */
  company?: string | null;
  /**
   * The testimonial text
   */
  text: string;
  /**
   * Star rating (1-5)
   */
  rating?: number | null;
  /**
   * Order in which testimonials appear
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Global site configuration and home page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Upload your site logo
   */
  logo?: (number | null) | Media;
  /**
   * Short company description used in footer
   */
  companyDescription?: string | null;
  headerInfo?: {
    email?: string | null;
    phone?: string | null;
    socialLinks?:
      | {
          label: string;
          url: string;
          /**
           * Emoji or text symbol (e.g. in, 𝕏, f)
           */
          icon: string;
          id?: string | null;
        }[]
      | null;
  };
  navigation?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  headerButton?: {
    label?: string | null;
    url?: string | null;
    openInNewTab?: boolean | null;
  };
  heroSection?: {
    /**
     * Small badge text above the title
     */
    badge?: string | null;
    /**
     * Main heading. Use line breaks for multi-line display.
     */
    title?: string | null;
    description?: string | null;
    primaryButtonText?: string | null;
    primaryButtonUrl?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonUrl?: string | null;
    /**
     * External image URL for hero section
     */
    heroImageUrl?: string | null;
    /**
     * Uploaded image overrides the URL field above
     */
    heroImage?: (number | null) | Media;
    /**
     * Small stats shown below buttons (e.g. 99.99% Uptime)
     */
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  statsSection?: {
    isVisible?: boolean | null;
    stats?:
      | {
          /**
           * e.g. 500+
           */
          value: string;
          /**
           * e.g. Happy Clients
           */
          label: string;
          iconName?:
            | (
                | 'Zap'
                | 'ShieldCheck'
                | 'Cloud'
                | 'Headphones'
                | 'Server'
                | 'Database'
                | 'Globe'
                | 'TrendingUp'
                | 'CheckCircle'
                | 'Star'
                | 'Award'
                | 'Users'
                | 'Cpu'
                | 'Lock'
                | 'BarChart2'
                | 'Rocket'
                | 'Shield'
                | 'Settings'
                | 'Mail'
                | 'Phone'
                | 'MapPin'
                | 'ArrowRight'
                | 'Clock'
                | 'Activity'
                | 'HardDrive'
                | 'Wifi'
                | 'Code'
                | 'Package'
              )
            | null;
          id?: string | null;
        }[]
      | null;
  };
  whyChooseSection?: {
    tag?: string | null;
    title?: string | null;
    description?: string | null;
    features?:
      | {
          iconName?:
            | (
                | 'Zap'
                | 'ShieldCheck'
                | 'Cloud'
                | 'Headphones'
                | 'Server'
                | 'Database'
                | 'Globe'
                | 'TrendingUp'
                | 'CheckCircle'
                | 'Star'
                | 'Award'
                | 'Users'
                | 'Cpu'
                | 'Lock'
                | 'BarChart2'
                | 'Rocket'
                | 'Shield'
                | 'Settings'
                | 'Mail'
                | 'Phone'
                | 'MapPin'
                | 'ArrowRight'
                | 'Clock'
                | 'Activity'
                | 'HardDrive'
                | 'Wifi'
                | 'Code'
                | 'Package'
              )
            | null;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Section heading/intro — actual service cards are managed in the Services collection
   */
  servicesSection?: {
    tag?: string | null;
    title?: string | null;
    description?: string | null;
  };
  awsSection?: {
    tag?: string | null;
    title?: string | null;
    description?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
    imageUrl?: string | null;
    /**
     * Upload overrides the URL above
     */
    sectionImage?: (number | null) | Media;
    features?:
      | {
          iconName?:
            | (
                | 'Zap'
                | 'ShieldCheck'
                | 'Cloud'
                | 'Headphones'
                | 'Server'
                | 'Database'
                | 'Globe'
                | 'TrendingUp'
                | 'CheckCircle'
                | 'Star'
                | 'Award'
                | 'Users'
                | 'Cpu'
                | 'Lock'
                | 'BarChart2'
                | 'Rocket'
                | 'Shield'
                | 'Settings'
                | 'Mail'
                | 'Phone'
                | 'MapPin'
                | 'ArrowRight'
                | 'Clock'
                | 'Activity'
                | 'HardDrive'
                | 'Wifi'
                | 'Code'
                | 'Package'
              )
            | null;
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  howItWorksSection?: {
    isVisible?: boolean | null;
    tag?: string | null;
    title?: string | null;
    description?: string | null;
    steps?:
      | {
          /**
           * e.g. 01
           */
          stepNumber: string;
          title: string;
          description: string;
          iconName?:
            | (
                | 'Zap'
                | 'ShieldCheck'
                | 'Cloud'
                | 'Headphones'
                | 'Server'
                | 'Database'
                | 'Globe'
                | 'TrendingUp'
                | 'CheckCircle'
                | 'Star'
                | 'Award'
                | 'Users'
                | 'Cpu'
                | 'Lock'
                | 'BarChart2'
                | 'Rocket'
                | 'Shield'
                | 'Settings'
                | 'Mail'
                | 'Phone'
                | 'MapPin'
                | 'ArrowRight'
                | 'Clock'
                | 'Activity'
                | 'HardDrive'
                | 'Wifi'
                | 'Code'
                | 'Package'
              )
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Section heading — actual pricing cards are managed in Pricing Plans collection
   */
  pricingSection?: {
    tag?: string | null;
    title?: string | null;
    description?: string | null;
  };
  /**
   * Section heading — FAQ items are managed in the FAQs collection
   */
  faqSection?: {
    tag?: string | null;
    title?: string | null;
    description?: string | null;
  };
  ctaSection?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    primaryButtonText?: string | null;
    primaryButtonUrl?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonUrl?: string | null;
  };
  /**
   * Section heading — testimonial cards are managed in the Testimonials collection
   */
  testimonialsSection?: {
    tag?: string | null;
    title?: string | null;
    description?: string | null;
  };
  contactSection?: {
    tag?: string | null;
    title?: string | null;
    description?: string | null;
    formTitle?: string | null;
  };
  footerAddress?: string | null;
  footerPhone?: string | null;
  footerEmail?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactAddress?: string | null;
  contactPhoneHours?: string | null;
  heroTitle?: string | null;
  heroDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-items".
 */
export interface AboutItem {
  id: number;
  /**
   * Emoji icon for the card
   */
  icon: string;
  title: string;
  description: string;
  /**
   * Order in which items appear
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently Asked Questions shown on the home page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'hero';
        value: number | Hero;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'about-items';
        value: number | AboutItem;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  primaryButtonText?: T;
  secondaryButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  icon?: T;
  iconName?: T;
  title?: T;
  description?: T;
  imageUrl?: T;
  serviceImage?: T;
  learnMoreUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  period?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  isPopular?: T;
  buttonText?: T;
  buttonUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  text?: T;
  rating?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  companyDescription?: T;
  headerInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        socialLinks?:
          | T
          | {
              label?: T;
              url?: T;
              icon?: T;
              id?: T;
            };
      };
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  headerButton?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
      };
  heroSection?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        primaryButtonText?: T;
        primaryButtonUrl?: T;
        secondaryButtonText?: T;
        secondaryButtonUrl?: T;
        heroImageUrl?: T;
        heroImage?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  statsSection?:
    | T
    | {
        isVisible?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              iconName?: T;
              id?: T;
            };
      };
  whyChooseSection?:
    | T
    | {
        tag?: T;
        title?: T;
        description?: T;
        features?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        tag?: T;
        title?: T;
        description?: T;
      };
  awsSection?:
    | T
    | {
        tag?: T;
        title?: T;
        description?: T;
        buttonText?: T;
        buttonUrl?: T;
        imageUrl?: T;
        sectionImage?: T;
        features?:
          | T
          | {
              iconName?: T;
              title?: T;
              id?: T;
            };
      };
  howItWorksSection?:
    | T
    | {
        isVisible?: T;
        tag?: T;
        title?: T;
        description?: T;
        steps?:
          | T
          | {
              stepNumber?: T;
              title?: T;
              description?: T;
              iconName?: T;
              id?: T;
            };
      };
  pricingSection?:
    | T
    | {
        tag?: T;
        title?: T;
        description?: T;
      };
  faqSection?:
    | T
    | {
        tag?: T;
        title?: T;
        description?: T;
      };
  ctaSection?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        primaryButtonText?: T;
        primaryButtonUrl?: T;
        secondaryButtonText?: T;
        secondaryButtonUrl?: T;
      };
  testimonialsSection?:
    | T
    | {
        tag?: T;
        title?: T;
        description?: T;
      };
  contactSection?:
    | T
    | {
        tag?: T;
        title?: T;
        description?: T;
        formTitle?: T;
      };
  footerAddress?: T;
  footerPhone?: T;
  footerEmail?: T;
  contactEmail?: T;
  contactPhone?: T;
  contactAddress?: T;
  contactPhoneHours?: T;
  heroTitle?: T;
  heroDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-items_select".
 */
export interface AboutItemsSelect<T extends boolean = true> {
  icon?: T;
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}